// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../Utility/DllImports.fs"
      "../Utility/ArrayFunctions.fs"
      "../Utility/Math.fs"
      "../Utility/Format.fs"
      "../Utility/Utility.fs"
      "../Geography/Geography.Celestial.fs"
      "../Geography/Geography.Station.fs"
      "../Geography/Geography.Starbase.fs"
      "../Geography/Geography.System.fs"
      "../Product/Product.Types.fs"
      "../Product/Product.Records.fs"
      "../Product/Product.fs"
      "../Ice/Ice.Types.fs"
      "../Ice/Ice.Records.fs"
      "../Ice/Ice.fs"
      "../Ore/Ore.Types.fs"
      "../Ore/Ore.Records.fs"
      "../Ore/Ore.fs"
      "../Character/Skill.fs"
      "../Character/Implant.fs"
      "../Character/Character.fs"
      "../Data/Data.Collections.fs"
      "../Data/Data.Character.fs"
      "../Data/Data.Skills.fs"
      "../Data/Data.Implants.fs"
      "../Industry/Blueprint.Types.fs"
      "../Industry/Blueprint.Records.fs"
      "../Industry/Blueprint.Parser.fs"
      "../Industry/Blueprint.fs"
      "../Industry/Job.fs"
      "../Industry/Reprocess.fs"
      "../Market/Market.Providers.fs"
      "../Market/Market.Types.fs"
      "../Market/Market.Records.fs"
      "../Market/Market.Parser.fs"
      "../Market/Market.Crest.fs"
      "../Market/Market.fs"
      "../CrestLogin.fs"
      "../DataCache.fs"
      "../Interop.fs"
      "../ExampleDU.fs"
